### ISSUE TITLE
Replace npm package 'vscode' with @types/vscode and vscode-test

### ISSUE THREAD

**Issue by sag-tgo** [CaribouJohn/vscode-apama-extensions#27]
https://www.npmjs.com/package/vscode
This package is deprecated

I have done some work on this as part of changes on this branch:
https://github.com/sag-tgo/vscode-apama-extensions/tree/feature/project-view
But it may be better/cleaner to start again and follow the migration guide:
https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Comment by CaribouJohn** [comment]
Will be looking into this - will chat with you about it tomorrow.

**Comment by CaribouJohn** [comment]
added @types/vscode
